# Generated by Django 4.1.13 on 2024-08-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_project_descrption_project_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='descrption',
            field=models.TextField(),
        ),
    ]
